AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

  Exclude:
    - '**/*.md'
    - '**/*.markdown'
    - 'benchmark/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'

require:
  - rubocop-md
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

# We do not need to support Ruby 1.9, so this is good to use.
Style/SymbolArray:
  Enabled: true

# Most readable form.
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Exclude:
    - README.md
    - benchmark/**/*

Metrics/BlockLength:
  Exclude:
    - examples/**/*
    - fix.gemspec

Metrics/ParameterLists:
  Max: 6

Naming/FileName:
  Exclude:
    - CODE_OF_CONDUCT.md
    - LICENSE.md
    - README.md

Style/ClassAndModuleChildren:
  Exclude:
    - README.md

Naming/BlockForwarding:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false
