AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

  Exclude:
    - spec/**/*.rb

require:
  - rubocop-performance
  - rubocop-md
  - rubocop-rake
  - rubocop-thread_safety

Style/StringLiterals:
  EnforcedStyle: double_quotes

# We do not need to support Ruby 1.9, so this is good to use.
Style/SymbolArray:
  Enabled: true

# Most readable form.
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Exclude:
    - README.md
    - benchmark/**/*

Metrics/BlockLength:
  Exclude:
    - examples/**/*
    - fix.gemspec

Metrics/ParameterLists:
  Max: 6

Naming/FileName:
  Exclude:
    - CODE_OF_CONDUCT.md
    - LICENSE.md
    - README.md

Style/ClassAndModuleChildren:
  Exclude:
    - README.md
