language: ruby
sudo: false
cache: bundler
branches:
  only: master
before_install:
  - gem install bundler
script:
  - bundle exec rake test
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
matrix:
  allow_failures:
    - rvm: 2.3
    - rvm: ruby-head
  fast_finish: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a44b19cc5cf6db25fa87
    on_success: change
    on_failure: always
    on_start: never
