#!/usr/bin/env ruby

require 'digest/sha2'

gemname         = :fix
ARGV[0]         = File.read('VERSION.semver').chomp if ARGV[0].nil?
built_gem_path  = "pkg/#{gemname}-#{ARGV[0]}.gem"
checksum        = Digest::SHA512.new.hexdigest(File.read(built_gem_path))
checksum_path   = "checksum/#{gemname}-#{ARGV[0]}.gem.sha512"

File.open(checksum_path, 'w') { |f| f.write("#{checksum}\n") }
