title: Fix specing framework
author:
  name: Cyril Kato
description: >
  Fix is a modern Ruby testing framework built around a key architectural principle:
  the complete separation between specifications and tests. It allows you to write
  pure specification documents that define expected behaviors, and then independently
  challenge any implementation against these specifications.
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
minima:
  skin: auto
  social_links:
    - { platform: github,     user_url: "https://github.com/fixrb/fix" }
    - { platform: x,          user_url: "https://x.com/fix_rb" }
feed:
  icon: /favicon.png
  logo: /favicon.png
  posts_limit: 100
